//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TChampLie
    {
        public int TCLie_PK_ID { get; set; }
        public string TCLie_Valeur { get; set; }
        public int TCLie_Ordre { get; set; }
        public string TCLie_ChampTInd { get; set; }
        public string TClie_LabelFr { get; set; }
        public string TClie_LabelEn { get; set; }
    }
}
